spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: admin
#    url: jdbc:mariadb://127.0.0.1:3306/NewsPro?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
    url: jdbc:mariadb://47.111.104.53:3306/NewsPro?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8888
  servlet:
    context-path: /news

logging:
  level:
    com.news.manage: info
  config:
    classpath: log4j.properties

