spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: admin
    url: jdbc:mariadb://127.0.0.1:3306/NewsPro?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
#    url: jdbc:mariadb://47.111.104.53:3306/NewsPro?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  #以下为新增
  druid:
    # 指明是否在从池中取出连接前进行检验,如果检验失败, 则从池中去除连接并尝试取出另一个，
    #注意: 设置为true后如果要生效,validationQuery参数必须设置为非空字符串
    test-on-borrow: false
    # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除.
    #注意: 设置为true后如果要生效,validationQuery参数必须设置为非空字符串
    test-while-idle: false
    # 指明是否在归还到池中前进行检验，注意: 设置为true后如果要生效,
    #validationQuery参数必须设置为非空字符串
    test-on-return: false
    # SQL查询,用来验证从连接池取出的连接,在将连接返回给调用者之前.
    #如果指定,则查询必须是一个SQL SELECT并且必须返回至少一行记录
    validation-query: select 1

server:
  port: 8888
  servlet:
    context-path: /news

logging:
  level:
    com.news.manage: info
  config:
    classpath: log4j.properties

