spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username:
    password:
    url:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8888
  servlet:
    context-path: /news

logging:
  level: info
